"""002 - remove is_active from all tables

Revision ID: a953daaae3f9
Revises: aaa446a545f8
Create Date: 2026-05-18 22:56:05.568747

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a953daaae3f9"
down_revision = "aaa446a545f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("distributor_stocks", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("uq_distributor_stocks_product_id_distributor_id")
        )
        batch_op.create_unique_constraint(
            "uq_distributor_stocks_product_id_distributor_id",
            ["product_id", "distributor_id"],
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("payment_methods", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
            )
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
            )
        )

    with op.batch_alter_table("payment_methods", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
            )
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
            )
        )

    with op.batch_alter_table("distributor_stocks", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_distributor_stocks_product_id_distributor_id", type_="unique"
        )
        batch_op.create_index(
            batch_op.f("uq_distributor_stocks_product_id_distributor_id"),
            ["product_id", "distributor_id"],
            unique=1,
        )

    with op.batch_alter_table("customers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.BOOLEAN(), server_default=sa.text("1"), nullable=False
            )
        )

    # ### end Alembic commands ###
